spring:
  application:
    name: demo
#   ????????? web-application-type: none ????? ????????? ??? ??????,
#  ??? ??? ? ??? ??? ???????????
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/pokemon_db
    username: pokemon_user
    password: pokemon_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#pokemon:
#  search:
#    name: psyduck
